
name: My WorkFlow

on:
  push:
    branches: [ "main" ]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

  #  - name: List and Cat file in Repo
  #    run: |
  #      echo "My first GitHub Action"
  #      ls
  #      cat README.md
      
    #- name: List Files
    #  run: ls
      
    #- name: Read Files
    #  run: cat README.md  
    - name: Executing shell Script
      run: |
        chmod +x shellscript.sh
        ./shellscript.sh

  